name: Purge Camo Cache

on:
  push:                   # push時に実行
    branches:
      - main              # mainブランチにpushされた時のみ
  workflow_dispatch:      # 手動実行
  schedule:
    - cron: "0 0 * * *"   # 毎日0時に実行

jobs:
  purge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Run purge script
        run: node src/cache_purge.mjs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
